### ISSUE TITLE
Support Pagination

### ISSUE THREAD

**Issue by dreamlibrarian** [infobloxopen/infoblox-go-client#118] opened 2021-02-19 20:44 UTC
I'm leveraging this library for a usecase that wants to perform large bulk queries against the database which may return more than 1000 results; GetObject has no pagination support as written, making large response sets a firm error case in the client. 

Would love a paginated GetObject.

**Comment by somashekhar** [comment] 2021-06-23 09:34
duplicate of #75. We can track it in one place.

**Closed by somashekhar** 2021-06-23 09:34 UTC
Labels: duplicate, enhancement
